server:
  port: 8088

#数据库
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://172.16.2.11:3306/zhf-gkpt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: 9Tg($<77x+N.
#          driver: com.p6spy.engine.spy.P6SpyDriver
          driver: com.mysql.cj.jdbc.Driver
          #connectionInitSqls: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
        ds1:
#          url: jdbc:p6spy:mysql://172.16.2.11:3306/egin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
          url: jdbc:mysql://172.16.2.11:3306/egin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
          username: root
          password: 9Tg($<77x+N.
          driver: com.mysql.cj.jdbc.Driver

#打印sql
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.example.demo.modules.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 启用http上传
servlet:
  multipart:
    enabled: true
    max-file-size: 50MB
    max-request-size: 60MB

#线程池
threadPool:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 5

#sa-token
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 600
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 300
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false