spring:
  profiles:
    active: dev
  application:
      name: demo
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#打印sql
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.example.demo.modules.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#线程池
threadPool:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 5

#启用http上传
servlet:
  multipart:
    enabled: true
    max-file-size: 50MB
    max-request-size: 60MB

#sa-token
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: gkptToken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 600
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 300
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false


#用于解码URI的字符编码。
server:
  tomcat:
    uri-encoding: UTF-8
log:
  path: ./logs
logging:
  config: classpath:config/logback-spring.xml