#数据库
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.2.11:3306/zhf-gkpt?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 9Tg($<77x+N.

#打印sql
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.example.demo.modules.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 启用http上传
servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 20MB

#线程池
threadPool:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 5

#sa-token
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 600
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 300
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false