server:
  port: 7777
  servlet:
    context-path: /july

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.2.11:3306/china_aero_engine?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 9Tg($<77x+N.

#打印sql
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.example.demo.modules.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
